source ~/.local/share/omadebian/defaults/zsh/rc

# EXPORT
export EDITOR="nvim"
export SUDO_EDITOR="$EDITOR"
export LESS='--chop-long-lines --HILITE-UNREAD --ignore-case --incsearch --jump-target=4 --LONG-PROMPT --no-init --quit-if-one-screen --RAW-CONTROL-CHARS --use-color --window=-4'
export RIPGREP_CONFIG_PATH=~/.config/ripgrep/ripgreprc

# Plugins
[ -f /usr/share/zsh-autosuggestions/zsh-autosuggestions.zsh ] && source /usr/share/zsh-autosuggestions/zsh-autosuggestions.zsh
[ -f /usr/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh ] && source /usr/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh

# Completion
autoload -Uz compinit && compinit

# Aliases
alias ls='eza -lh --group-directories-first --icons=auto'
alias lsa='ls -a'
alias lt='eza --tree --level=2 --long --icons --git'
alias lta='lt -a'
alias ff="fzf --preview 'batcat --style=numbers --color=always {}'"
alias fd='fdfind'
alias python="python3"
alias ld="lazydocker"
alias lg="lazygit"
alias zl="zellij"
alias sshh="cat ~/.ssh/config | grep \"Host \" | cut -d \" \" -f 2 | sort"
alias install='sudo apt install'
alias update='sudo apt update'
alias upgrade='sudo apt upgrade && sudo apt autoremove --purge'
alias purge='sudo apt autoremove --purge'
alias uu='echo "APT update & upgrade...\n " && sudo apt update && sudo apt upgrade -y && sudo apt autoremove --purge && update-all'
alias df='df -h'
alias free='free -h'
alias myip="hostname -I | awk '{print $1}'; curl -s ifconfig.me && echo ' external ip'"
alias x="exit"
alias p="less"
alias d='docker'
alias bat='batcat'
alias v="nvim"
alias n="nvim"
alias vim="nvim"
alias vv="nvim ."
alias cl="clear"
alias s="zsh -l"
alias vpn="sudo wg-quick up wg0"
alias vpnd="sudo wg-quick down wg0"

# Custom sources
[ -f "$HOME/.custom_aliases" ] && source "$HOME/.custom_aliases"
[ -f "$HOME/.env" ] && source "$HOME/.env"
