[env]
TERM = "xterm-256color"

[shell]
program = "zellij"

[window]
padding.x = 0
padding.y = 0
decorations = "None"
opacity = 0.93

[keyboard]
bindings = [
{ key = "F11", action = "ToggleFullscreen" }
]

[cursor]
style = { shape = "Block" }

